/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import db.Tools;

/**
 *
 * @author ok
 */
public class Suppliers extends javax.swing.JPanel {

    /**
     * Creates new form Suppliers
     */
    public Suppliers() {
        initComponents();
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        s1_id = new Control.Jtextfield(20);
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        s1_email = new Control.Jtextfield(20);
        jLabel8 = new javax.swing.JLabel();
        s1_company = new Control.Jtextfield(20);
        jLabel9 = new javax.swing.JLabel();
        s1_address = new Control.Jtextfield(20);
        jScrollPane2 = new javax.swing.JScrollPane();
        s1_table = new javax.swing.JTable();
        sname = new javax.swing.JRadioButton();
        sadd = new javax.swing.JButton();
        sclear = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        supdate = new javax.swing.JButton();
        s1_search = new Control.Jtextfield(25);
        sdelete = new javax.swing.JButton();
        sid = new javax.swing.JRadioButton();
        s_search = new javax.swing.JButton();
        s1_phone = new Control.Jtextfield(20);
        s1_name = new Control.Jtextfield(20);
        jButton1 = new javax.swing.JButton();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panels/icons8_businessman_64px.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 153));
        jLabel5.setText("Id");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel2.setText("Name");

        s1_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1_idActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 153));
        jLabel6.setText("Phone");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 153));
        jLabel7.setText("Email");

        s1_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1_emailActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 153));
        jLabel8.setText("Company");

        s1_company.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1_companyActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 153));
        jLabel9.setText("Address");

        s1_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1_addressActionPerformed(evt);
            }
        });

        s1_table.setForeground(new java.awt.Color(0, 102, 153));
        s1_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Phone", "Email", "Address", "Company"
            }
        ));
        s1_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s1_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(s1_table);

        buttonGroup1.add(sname);
        sname.setForeground(new java.awt.Color(0, 102, 153));
        sname.setText("Name");

        sadd.setBackground(new java.awt.Color(0, 102, 153));
        sadd.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        sadd.setForeground(new java.awt.Color(255, 255, 255));
        sadd.setText("Add");
        sadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saddActionPerformed(evt);
            }
        });

        sclear.setBackground(new java.awt.Color(0, 102, 153));
        sclear.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        sclear.setForeground(new java.awt.Color(255, 255, 255));
        sclear.setText("Clear");
        sclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sclearActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 153));
        jLabel10.setText("Search With");

        supdate.setBackground(new java.awt.Color(0, 102, 153));
        supdate.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        supdate.setForeground(new java.awt.Color(255, 255, 255));
        supdate.setText("Update");
        supdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supdateActionPerformed(evt);
            }
        });

        s1_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1_searchActionPerformed(evt);
            }
        });

        sdelete.setBackground(new java.awt.Color(0, 102, 153));
        sdelete.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        sdelete.setForeground(new java.awt.Color(255, 255, 255));
        sdelete.setText("Delete");
        sdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdeleteActionPerformed(evt);
            }
        });

        buttonGroup1.add(sid);
        sid.setForeground(new java.awt.Color(0, 102, 153));
        sid.setSelected(true);
        sid.setText("Id");

        s_search.setBackground(new java.awt.Color(0, 102, 153));
        s_search.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        s_search.setForeground(new java.awt.Color(255, 255, 255));
        s_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panels/icons8_search_32px_2.png"))); // NOI18N
        s_search.setText("Search");
        s_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_searchActionPerformed(evt);
            }
        });

        s1_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1_phoneActionPerformed(evt);
            }
        });

        s1_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1_nameActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 102, 153));
        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Show All Data ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sname)
                                .addGap(49, 49, 49)
                                .addComponent(sid)
                                .addGap(44, 44, 44)
                                .addComponent(s1_search, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(s_search, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(s1_id, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(s1_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(s1_name, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(s1_email, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(s1_address, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(s1_company, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(sdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(sclear, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(supdate, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(sadd, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(413, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s1_id, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s1_email, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(s1_name, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(s1_address, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s1_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s1_company, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sid)
                    .addComponent(sname)
                    .addComponent(jLabel10)
                    .addComponent(s1_search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s_search, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sclear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supdate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sadd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void s1_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s1_idActionPerformed

    private void s1_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s1_emailActionPerformed

    private void s1_companyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1_companyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s1_companyActionPerformed

    private void s1_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s1_addressActionPerformed
sup b=new sup();
    private void setvalues(){
       b.setId(Integer.parseInt(s1_id.getText()));
        b.setName(s1_name.getText());
        b.setPhone(s1_phone.getText());
        b.setEmail(s1_email.getText());
        b.setAddress(s1_address.getText());
         b.setCompany(s1_company.getText());
    }
    sup ob=new sup();
      private void ClearData(){
        Tools.clearText(this);
        s1_id.setText(b.getAutoNumber()); 
       s1_name.requestFocus(); 
    }
      
    private void saddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saddActionPerformed
        // TODO add your handling code here:
        
         setvalues();
        b.add();
        ClearData();
     ob.getAllRows(s1_table);
    }//GEN-LAST:event_saddActionPerformed

    private void sclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sclearActionPerformed
        // TODO add your handling code here:
         ClearData();
    }//GEN-LAST:event_sclearActionPerformed

    private void supdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supdateActionPerformed
        // TODO add your handling code here:
          setvalues();
        b.update();
        ClearData();
    ob.getAllRows(s1_table);
    }//GEN-LAST:event_supdateActionPerformed

    private void s1_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s1_searchActionPerformed

    private void s_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_searchActionPerformed
        // TODO add your handling code here:
        
           String sreachkey="select * from suptest1 where ";
        if(sid.isSelected()){
            sreachkey+="number";
        }
        else{
            sreachkey+="name";
        }
        sreachkey+=" like'%"+s1_search.getText()+"%'";
        b.getCustomRows(sreachkey, s1_table);
    }//GEN-LAST:event_s_searchActionPerformed

    private void s1_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s1_phoneActionPerformed

    private void s1_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s1_nameActionPerformed

    private void sdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdeleteActionPerformed
        // TODO add your handling code here:
         setvalues();
        b.delete();
        ClearData();
       ob.getAllRows(s1_table);
    }//GEN-LAST:event_sdeleteActionPerformed

    private void s1_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s1_tableMouseClicked
        // TODO add your handling code here:
        
          try{
            int row=s1_table.getSelectedRow();
            String sid=s1_table.getValueAt(row, 0).toString();
             String sname=s1_table.getValueAt(row, 1).toString();
           String sphone=s1_table.getValueAt(row, 2).toString();
           String semail=s1_table.getValueAt(row, 3).toString();
            String saddress=s1_table.getValueAt(row, 4).toString();
               String scompany=s1_table.getValueAt(row,5).toString();
            s1_id.setText(sid);
           s1_name.setText(sname);
            s1_phone.setText(sphone);
            s1_email.setText(semail);
            s1_address.setText(saddress);
           s1_company.setText(scompany);  
        }
        catch(Exception ex){
           Tools.msgBox(ex.getMessage()); 
        }
    }//GEN-LAST:event_s1_tableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ob.getAllRows(s1_table);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField s1_address;
    private javax.swing.JTextField s1_company;
    private javax.swing.JTextField s1_email;
    private javax.swing.JTextField s1_id;
    private javax.swing.JTextField s1_name;
    private javax.swing.JTextField s1_phone;
    private javax.swing.JTextField s1_search;
    private javax.swing.JTable s1_table;
    private javax.swing.JButton s_search;
    private javax.swing.JButton sadd;
    private javax.swing.JButton sclear;
    private javax.swing.JButton sdelete;
    private javax.swing.JRadioButton sid;
    private javax.swing.JRadioButton sname;
    private javax.swing.JButton supdate;
    // End of variables declaration//GEN-END:variables
}
